<body>
    <div class="container">
        <div class="p-3 m-2 border rounded shadow-sm">
            <h4>
                Welcome to Scratch.1                
            </h4>
            <hr class="my-1">
            <small>This page is dynamically generated by scratch framework.</small>

            <p>Let's Start the work!!</p>

            To edit this page:
            <div class="p-2 border bg-light m-2 mb-4">
                <b>View: </b> <?= Views ?>home.php
            </div>
            <div class="p-2 border bg-light m-2 ">
                <b>Controller: </b> <?= Controllers ?>Home.php
            </div>

            <i class="ml-4">
                To know more, visit <a href="<?= base_url('Userguide/') ?>">user guide</a>.
            </i>
        </div>
    </div>
</body>